const productArray = [
    {
        id: 1,
        productName: "How to win friends and influence people",
        productPrice: 3500,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./howtowinfriends.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "Dale Carnegie",
    },
    {
        id: 2,
        productName: "Secret of the millionaire mind",
        productPrice: 4500,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./4.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 3,
        productName: "Think and Gro Rich",
        productPrice: 9500,
        productQuantity: 4,
        productsCategory: "Personal Development, Self Help",
        productImage: "./thinkandgrow.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 4,
        productName: "Go Pro",
        productPrice: 6000,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./2.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 5,
        productName: "Steal like an artist",
        productPrice: 5000,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./3.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 6,
        productName: "Building an empire",
        productPrice: 3800,
        productQuantity: 8,
        productsCategory: "Relationship",
        productImage: "./4.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 7,
        productName: "Rich Dad poor Dad ",
        productPrice: 300,
        productQuantity: 34,
        productsCategory: "Relationship",
        productImage: "./richdad.jpeg",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "Robert T. Kiyosaki",
    },
    {
        id: 8,
        productName: "Business of the 21st century",
        productPrice: 2400,
        productQuantity: 9,
        productsCategory: "Relationship",
        productImage: "./1.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 9,
        productName: "10x Rule",
        productPrice: 3500,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./2.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 10,
        productName: "Prospecting Rule",
        productPrice: 6000,
        productQuantity: 24,
        productsCategory: "Relationship",
        productImage: "./3.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 11,
        productName: "The secret",
        productPrice: 1500,
        productQuantity: 14,
        productsCategory: "Relationship",
        productImage: "./4.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 12,
        productName: "Building to the last",
        productPrice: 11000,
        productQuantity: 5,
        productsCategory: "Relationship",
        productImage: "./1.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 13,
        productName: "How to be Great in business",
        productPrice: 4500,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./2.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 14,
        productName: "Richest man in Babilon",
        productPrice: 2500,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./3.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 15,
        productName: "Seven Habits of highly effetive people",
        productPrice: 3000,
        productQuantity: 10,
        productsCategory: "Leadership, personal success",
        productImage: "./7habits.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "Stephen R. Covey",
    },
    {
        id: 16,
        productName: "It ends with us",
        productPrice: 3500,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./itendwithus.jpeg",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 17,
        productName: "Who moved my cheese",
        productPrice: 3500,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./whomovechees.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 18,
        productName: "Your First Year in Network Marketing",
        productPrice: 1500,
        productQuantity: 50,
        productsCategory: "Marketing, Business",
        productImage: "./yourfirstyear.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "Mark Yarnell",
    },
    {
        id: 19,
        productName: "Network Marketing for Dummies",
        productPrice: 600,
        productQuantity: 34,
        productsCategory: "Marketing, Business",
        productImage: "./networkmarketingfordummies.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 20,
        productName: "Richest man in Babilon",
        productPrice: 3700,
        productQuantity: 12,
        productsCategory: "Relationship",
        productImage: "./1.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 21,
        productName: "It's Not How Good You Are, It's How Good You Want to Be",
        productPrice: 2900,
        productQuantity: 15,
        productsCategory: "Self help",
        productImage: "./It-s-Not-How-Good-You-Are-It-s-How-Good-You-Want-to-Be-9780714843377.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "Paul Arden",
    },
    {
        id: 22,
        productName: "Your Best Life Begins Each Morning",
        productPrice: 4000,
        productQuantity: 10,
        productsCategory: "Personal succcess, Self help",
        productImage: "./Your-Best-Life-Begins-Each-Morning-Osteen-Joel-9780446545099.webp",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "Joel Osteen",
    },
    {
        id: 23,
        productName: "Richest man in Babilon",
        productPrice: 3000,
        productQuantity: 4,
        productsCategory: "Relationship",
        productImage: "./4.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 24,
        productName: "Richest man in Babilon",
        productPrice: 7500,
        productQuantity: 5,
        productsCategory: "Relationship",
        productImage: "./1.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 25,
        productName: "Richest man in Babilon",
        productPrice: 2500,
        productQuantity: 7,
        productsCategory: "Relationship",
        productImage: "./2.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 26,
        productName: "Richest man in Babilon",
        productPrice: 200,
        productQuantity: 7,
        productsCategory: "Relationship",
        productImage: "./3.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 27,
        productName: "Richest man in Babilon",
        productPrice: 2300,
        productQuantity: 7,
        productsCategory: "Relationship",
        productImage: "./4.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
    {
        id: 28,
        productName: "Richest man in Babilon",
        productPrice: 2000,
        productQuantity: 7,
        productsCategory: "Relationship",
        productImage: "./1.avif",
        productDescription: "this is an highly motivatiol book that will affect your life possitively in the course of your career so if you are reading this book it means you are really a fans of change and you want a better future for yourself, so take your and read the book carefully",
        productAuthor: "",
    },
]
export default productArray